### PR TITLE
support grpo training v2

### PR DESCRIPTION
**Pull request by LSX-Sneakerprogrammer**
Considering making changes consistent with the newest main branch, this is a new version to support grpo training based on #455.

* Use `--activate_grpo` in `train_ppo.py` to activate grpo training
* calculate grpo advantanges in `process_experiences` function

Thanks for your time on reviewing this PR :)

### CODE REVIEW

**Comment by hijkzzz** [comment]
Great MR! I think we could support both REINFORCE and GRPO in this MR. One way to achieve this would be to replace --activate_grpo with an-- advantage_estimator parameter, which could accept values like ["gae", "group_norm", "reinforce"]. Then, if --critic_pretrain is None and advantage_estimator is set to either "group_norm" or "reinforce", we can disable the value network. I think this approach might be a bit more versatile.

**Comment by LSX-Sneakerprogrammer** [comment]
> advantage_estimator parameter,

Hi, I update the code supporting `--advantage_estimator` parameter which accepts values ["gae", "group_norm"] now.

**Comment by LSX-Sneakerprogrammer** [comment]
> rank1]: Traceback (most recent call last): [rank1]: File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main [rank1]: return _run_code(code, main_globals, None, [rank1]: File "/usr/lib/python3.10/runpy.py", line 86, in _run_code [rank1]: exec(code, run_globals) [rank1]: File "/home/OpenRLHF-group_norm/openrlhf/cli/train_ppo.py", line 429, in [rank1]: train(args) [rank1]: File "/home/OpenRLHF-group_norm/openrlhf/cli/train_ppo.py", line 268, in train [rank1]: trainer.fit(args, prompts_dataloader, pretrain_dataloader, consumed_samples, num_update_steps_per_episodes) [rank1]: File "/home/OpenRLHF-group_norm/openrlhf/trainer/ppo_trainer.py", line 229, in fit [rank1]: self.experience_maker.make_experience_list(rand_prompts, **self.generate_kwargs) [rank1]: File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context [rank1]: return func(*args, **kwargs) [rank1]: File "/home/OpenRLHF-group_norm/openrlhf/trainer/ppo_utils/experience_maker.py", line 226, in make_experience_list [rank1]: experiences = self.process_experiences(experiences) [rank1]: File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context [rank1]: return func(*args, **kwargs) [rank1]: File "/home/OpenRLHF-group_norm/openrlhf/trainer/ppo_utils/experience_maker.py", line 392, in process_experiences [rank1]: return [sum(experiences)] [rank1]: File "/home/OpenRLHF-group_norm/openrlhf/trainer/ppo_utils/experience_maker.py", line 107, in **add** [rank1]: sequences=conditional_cat(self.sequences, other.sequences), [rank1]: File "/home/OpenRLHF-group_norm/openrlhf/trainer/ppo_utils/experience_maker.py", line 39, in conditional_cat [rank1]: return op(attr1, attr2) [rank1]: File "/home/OpenRLHF-group_norm/openrlhf/trainer/ppo_utils/experience_maker.py", line 36, in [rank1]: op = lambda x, y: torch.cat((x, y), dim=0) [rank1]: RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 741 but got size 769 for tensor number 1 in the list.
> 
> When I use --advantage_estimator = group_norm, the following error occurs in the program，Can I get your wechat please?

Hi, please refer to the newest group_norm mr https://github.com/OpenRLHF/OpenRLHF/pull/514, which we did lots of experiments to ensure the correctness.

**Comment by GDzhu01** [comment]
https://github.com/OpenRLHF/OpenRLHF/pull/514 Doesn't seem to solve the problem I mentioned because I can't use --packing_samples in train_ppo_llama.sh

**Pull request closed without merging**
